sudo: false
language:
- java
- node_js
node_js:
- '10'
services:
- docker
jdk:
- openjdk11
addons:
  sauce_connect: true
env:
- TERM=dumb
install:
- cd web && npm run init
- cd ../bundles && ./gradlew --version
- cd ..
script:
- (cd web && npm run build-prod)
- (cd bundles && ./gradlew --no-daemon build --continue -x check)
- (cd bundles && ./gradlew --no-daemon export -x check)
- (cd bundles/specmate-std-env/generated/distributions/executable/ && java -Xmx6000m -Djdk.crypto.KeyAgreement.legacyKDF=true -jar dev-specmate-all.jar &)
- sleep 10
- (cd ui-tests/ && mvn clean test)
- (cd bundles && ./gradlew --no-daemon check)
after_success:
- DOCKER_TAG=$TRAVIS_BRANCH
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t ${DOCKER_USERNAME}/specmate:${DOCKER_TAG} .
- docker push ${DOCKER_USERNAME}/specmate:${DOCKER_TAG}
- (cd bundles/specmate-std-env/generated/distributions/executable/&& mv dev-specmate-all.jar dev-specmate-all-$TRAVIS_TAG.jar)
- (cd bundles/specmate-std-env/generated/distributions/executable/&& mv prod-specmate-all.jar prod-specmate-all-$TRAVIS_TAG.jar)
- (cd bundles/specmate-std-env/generated/distributions/executable/&& mv prod-specmate-cdo-server.jar prod-specmate-cdo-server-$TRAVIS_TAG.jar)
- (cd bundles/specmate-std-env/generated/distributions/executable/&& mv prod-specmate-no-cdo-server.jar prod-specmate-no-cdo-server-$TRAVIS_TAG.jar)
cache:
  directories:
  - cnf/cache/stable
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eUiVeNw9rlpcaXi+bpoV4B4WFEjXCgBn6td9NRXFF9dOcJiozn5oHh6qk8g6kMHuUrGDCKcOo5fitxkNaoV1vqxNuRjo7ssPN3yG3QcUmIlsMHM2ueM+9AEyQxP1SuNXku/Vb+ATQ1F7jWUlWotcCWTPbELuhUvziwcF4zYWm2jcTL1twD3gCT9GFdovqnUnmVLHrUha4EUO8bwFlJmyaSmxH5RpcTbKK2tRagRlv/4yUajhBxaNgCXD2nBpNtV6nb2sPbybilB9gRO5d4oPurNQWb28aiobGm0+hNU5bG+MYOyF3fJWU7NaQ0tQP0M8zZ5QM/Lw8g/xMOdMaqZ2rHWPNyxFqNFsUa+H1S9f+tEmje+kvTZ7oPZRuzy90dYC1ZzwpuhG9y3qIlpnDs+9E+JRU3yASEWeb7VVZFrMJKK3wh/FEvVCduYKoTYgcckFeipkjQY1V/umfKRrlq/3ZFATBX3PKaUnHzctZ+KK2nEWBiYMLacw8JKqQSjTIGRchjLZHYpuTR2CuttfBHVH1kDs0SNd7mKsFQShzXfPDylHTT0ZyfVJ++IKaf1Ww37dmqui0FTULmVTy1vtmkcImpFX0y9WFWoOy1vI7QWM4U3YfasRBZlIigNNyLgPR3Bzg+Z+6YBVUdi4T/ulsDf7iU7ZEOD5g7fl06gfcDAKr9E=
  file: 
    - bundles/specmate-std-env/generated/distributions/executable/dev-specmate-all-$TRAVIS_TAG.jar
    - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-all-$TRAVIS_TAG.jar
    - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-cdo-server-$TRAVIS_TAG.jar
    - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-no-cdo-server-$TRAVIS_TAG.jar
  on:
    repo: junkerm/specmate
    condition: $TRAVIS_TAG =~ ^v[\.0-9]+(-dev-[0-9]+)?$
    tags: true
